# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Selenium Web Test (JS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
        chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
    - name: Install Firefox
      run: |
        sudo apt install firefox
    - name: Install Selenium
      run: |
        npm install selenium-webdriver
    - name: Install chromedriver and geckodriver (Firefox)
      run: |
        chmod +x ./scripts/chromedriver.sh ./scripts/geckodriver.sh
        ./scripts/chromedriver.sh
        ./scripts/geckodriver.sh 
